### PR TITLE
Fix `no_std` feature gate for num_traits

### PR DESCRIPTION
**Pull request by eflukx**
Add `no_std` feature gate for num_traits

### CODE REVIEW

**Comment by mjaakkol** [comment]
Me not having no_std environment and flying in dark when making tunings for the environment seems to lead me into repeated embarrassments. I appreciate adding no_std functionality but I was wondering if that's a big overkill. The reason why I added the config option was to keep clippy happy in std-environment and I thought that the little cfg trick would have worked (which it clearly didn't and thanks for pointing that out). I'm not a big fan of using macros to turn warnings off but in this case with good comment that's probably the right way to do as then no users needs to worry about setting or unsetting no_std feature but they can just use the crate. Just adding #[allow(unused_imports)] before the num_trait should do the trick. It is not like the asset has any codepaths needing no_std/std logic so the code change was there just to suppress the warning. Any thoughts?

I need to really set no_std environment for myself.

**Comment by eflukx** [comment]
> Me not having no_std environment and flying in dark when making tunings for the environment seems to lead me into repeated embarrassments. 

Haha.. no worries! Happy with you making this nice lib _and_ making it available open source.  Very much appreciated :)

Setting up a `no_std` environment for testing should be pretty straightforward. That said, as I'm just getting some Rust flight hours under my belt for myself, I'm really not the one to tell what the best approach would be for this (from a driver dev perspective). Other then just compiling for a `no_std` target that is..

Anyway, FWIW I see a lot of crates/drivers/lib out in the wild that use a feature flag for setting no_std/std environments..

**Comment by mjaakkol** [comment]
I took fixed crate into use (I've used it in some of my later packages) to ensure better accuracy and remove floating point dependency completely. It is in branch "fixed" (not referring the issue but using fixed point). Would you mind check if it compiles nicely in your environment. I added test cases so the algorithm should work.

If it works, I'll make this into another release and call that 1.0.

**Comment by eflukx** [comment]
> I took fixed crate into use (I've used it in some of my later packages) to ensure better accuracy and remove floating point dependency completely. It is in branch "fixed" (not referring the issue but using fixed point). Would you mind check if it compiles nicely in your environment. I added test cases so the algorithm should work.

Nice solution: dropping the float altogether!
Yes, the 'fixed' branch (commit 67079e8ca51) compiles and runs fine for my (no_std, ARM Cortex-m) target!

I don't know the `fixed` crate, but is the `FP::from_bits()` function platform/implementation independent? I.e. does this work the same across all platforms?

    let k = FP::from_bits(0x1112666);  // 273.15
    let m = FP::from_bits(0x119eb8);   // 17.62
    let t_n = FP::from_bits(0xf335c2); // 243.21

If so, I think we're good to go on **v1.0** 🥇

**Comment by mjaakkol** [comment]
Fixed-point math is great when the range is well defined as it allows all the bits used the best possible way without needing to waste space for exponent. The "bits" part refers how the integer bits are split between whole number and the fraction. When one uses fixed they need to decide how much is reserved for whole and fractional parts and it is done per bits bases. In my case, I used I16F16 and expressing the numbers in hex to keep my sanity. Those bits are not related to underlying machine architecture but how the number is split. There is fixed-macro crate that would help to do the manual calculations for me but it doesn't work in no_std (been there and done that).

**Comment by eflukx** [comment]
Great. I've done (manual) fixed point math before, but that was in a long-gone era :)

> The "bits" part refers how the integer bits are split between whole number and the fraction.
I see the argument to `::from_bits` is the `value * (1 << 16)`; makes sense.. 

Happy with your fix, thanks!

**Comment by eflukx** [comment]
Oh, and.. **congrats with your v1.0**  😉

**Comment by mjaakkol** [comment]
Thanks and it is our v1.0 :-)

Thanks for your contributions.

**Pull request closed without merging**
